<article id="<?= $article['id']; ?>">
<h2><?php if (isset($comments)): ?> <a href="/">&larr;</a> 
<?php endif; ?>
  <a href="/article/<?= $article['id']; ?>"><?= $article['title']; ?></a>
            
          </h2>
          <h5 "><span class="glyphicon glyphicon-time"></span>
            Автор
            <?= $article['author']; ?>,

            <?php echo (new \DateTime())->format('Y-m-d'); ?>
          </h5>
          <?php if (isset($comments)): ?>
          <?= $article['text']; ?>
          <?php else: ?>
          <p>
              <h4>
              <?= $article['description']; ?>
            </h4>
          </p>
          <?php endif; ?>
</article>

