<form class="answer-form" id="" role="form" method="POST" action="">
    <div class="form-group"><label for="author">Имя Автора</label>
        <input value="<?= $_SESSION['author'] ?? $formData['author'] ?? ''; ?>" name="comment[author]" type="text"
            class="form-control has-feedback" id="author" placeholder="Имя Автора"></div>
    <div class="form-group">
        <textarea wrap="hard" name="comment[body]" class="form-control" rows="5" cols="100" autocomplete="off"><?= $formData['body'] ?? ''; ?></textarea>
    </div>
    <input id="prodId" name="comment[parent_id]" type="hidden" value="<?= $comment['id'] ?? '0'; ?>">
    <button type="submit" class="btn btn-success">Submit</button>
</form>