<div id="comment-<?= $comment['id']; ?>" class="col-sm-12 comment">
    <h4> <?= $comment['author'] ?? 'Анонимно'; ?> <small><?= $comment['created_at'] ?? 'Дата неизвестна'; ?></small></h4>
    <p>
        <?= $comment['body'] ?? '<i>Комментарий скрыт</i>'; ?>
    </p>
    <a class="answer" href="#comment-<?= $comment['id'] ?? '0'; ?>">Answer</a>
    <?php include 'comment.form.phtml'; ?>
    <br>