<?php 
?>
        <h4>Leave a Comment:</h4>
        <form role="form">
          <div class="form-group">
            <textarea class="form-control" rows="3" required></textarea>
          </div>
          <button type="submit" class="btn btn-success">Submit</button>
        </form>
        <br><br>


<p><span class="badge"><?= $countComments; ?></span> Comments:</p><br>

<?php if (!empty($comments)): Utilities\echoComments($comments); endif; ?>