</div>

</div>

</body>
<script>
$( document ).ready(function() {

    $('.answer').click(function() {
        const linkedForm = $(this).next();
		$('.comment > .answer-form').not(linkedForm).hide();
        linkedForm.toggle();

    });
    $( "form" ).submit(function( event ) {
        event.preventDefault();
        const formData = $(this).serialize();
        $.ajax({
            type: "POST",
            url: "",
            data: formData,
            dataType: "text",
            success: function (response) {
                const newComment = $.parseJSON(response);
                $('#comment-' + newComment['parent_id']).load('/article/71 #comment-' + newComment['id']);
            }
        });
    });
});


</script>
</html>