</div>

</div>

</body>
<?php if (isset($comments)): ?>
<script>
$( document ).ready(function() {
    $(this).on("click", ".answer", function () {
        const linkedForm = $(this).next();
		$('.comment > .answer-form').not(linkedForm).hide();
        linkedForm.toggle();
    });
    $(this).on("submit", "form", function (event) {
        event.preventDefault();
        const formData = $(this).serialize();
        $.ajax({
            type:     "POST",
            url:      "",
            data:     formData,
            dataType: "text",
            success: function (response) {
                const newComment = $.parseJSON(response);
                $.get('', function(data) {
                    comment = $(data).find('#comment-' + newComment['id']);
                    $('#comment-' + newComment['parent_id']).append(comment);
                });
            }
        });
    });
});


</script>
<?php endif; ?>
</html>