<?php include 'head.phtml'; ?>
    <?php  include 'pager.phtml'; ?>
        <?php if (empty($articles)): ?>
        <h1>Не создано ни одной новости</h1>
        <?php endif; ?>
        <?php foreach ($articles as $article): ?>
        <?php  include 'article.phtml'; ?>
        <a href="/article/<?= $article['id']; ?>">Читать далее</a>
        <?php endforeach; ?>

      </div>
      <?php  include 'pager.phtml'; ?>
<?php include 'foot.phtml'; ?>