<?php include 'head.phtml'; ?>

                <form method="POST" action="/articles">
                <?php if (isset($errors['db'])): ?>
                    <div class="alert alert-danger">Ошибка при отправке <?= $errors['db']; ?></div>
                    <?php endif; ?>
                    <div class="form-group"><label for="author">Имя Автора</label>
                    <?php if (isset($errors['author'])): ?>
                    <p class="bg-warning">Укажите имя Автора</p>
                    <?php endif; ?>
                    <input value="<?= $_SESSION['author'] ?? $formData['author'] ?? ''; ?>" name="article[author]" type="text"
                            class="form-control has-feedback" id="author" placeholder="Имя Автора" ></div>
                    <div class="form-group"><label for="title">Заголовок</label>
                    <?php if (isset($errors['title'])): ?>
                    <p class="bg-warning">Добавьте заголовок</p>
                    <?php endif; ?>
                    <input value="<?= $formData['title'] ?? ''; ?>" name="article[title]" autocomplete="off" type="text" class="form-control"
                            id="description" placeholder="Короткое описание"></div>
                    <div class="form-group"><label for="description">Короткое описание</label>
                    <?php if (isset($errors['description'])): ?>
                    <p class="bg-warning">Необходимо короткое описание</p>
                    <?php endif; ?>
                    <input value="<?= $formData['description'] ?? ''; ?>" name="article[description]" autocomplete="off" type="text" class="form-control"
                            id="description" placeholder="Короткое описание"></div>
                    <div class="form-group"><label  for="body">Текст статьи</label>
                    <?php if (isset($errors['text'])): ?>
                    <p class="bg-warning">Заполните содержимое статьи</p>
                    <?php endif; ?>
                            <textarea wrap="hard" name="article[text]" class="form-control" rows="10" autocomplete="off"><?= $formData['text'] ?? ''; ?></textarea>
                        </div>

                    <input type="submit" class="btn btn-default" value="Отправить">
                </form>
<?php include 'foot.phtml'; ?>