<?php include 'head.phtml'; ?>

                <form method="POST" action="/articles">
                    <div class="form-group"><label for="author">Имя Автора</label>
                    <input value="<?= $_SESSION['author'] ?? $formData['author'] ?? ''; ?>" name="article[author]" type="text"
                            class="form-control has-feedback" id="author" placeholder="Имя Автора" ></div>
                    <div class="form-group"><label for="title">Заголовок</label>

                    <input value="<?= $formData['title'] ?? ''; ?>" name="article[title]" autocomplete="off" type="text" class="form-control"
                            id="description" placeholder="Короткое описание"></div>
                    <div class="form-group"><label for="description">Короткое описание</label>

                    <input value="<?= $formData['description'] ?? ''; ?>" name="article[description]" autocomplete="off" type="text" class="form-control"
                            id="description" placeholder="Короткое описание"></div>
                    <div class="form-group"><label  for="body">Текст статьи</label>

                            <textarea wrap="hard" name="article[text]" class="form-control" rows="10" autocomplete="off"><?= $formData['text'] ?? ''; ?></textarea>
                        </div>

                    <input type="submit" class="btn btn-default" value="Отправить">
                </form>
<?php include 'foot.phtml';?>