DROP TABLE IF EXISTS "articles" CASCADE;
CREATE TABLE "articles" (
    id          INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    author      VARCHAR(255) NOT NULL,
    title       VARCHAR(255) NOT NULL
    description VARCHAR(255) NOT NULL,
    body        TEXT NOT NULL,
    created_at  timestamp DEFAULT now(),
    updated_at  timestamp DEFAULT now(),
    deleted_at  timestamp
);
DROP TABLE IF EXISTS "comments" CASCADE;
CREATE TABLE "comments" (
    id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    author      VARCHAR(255) NOT NULL,
    article_id  INTEGER REFERENCES articles (id) ON DELETE RESTRICT,
    parent_id   INTEGER DEFAULT '0',
    body        INTEGER(400),
    updated_at  timestamp DEFAULT now(),
    deleted_at  timestamp
);