<!DOCTYPE html>
<html lang="en">

<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>

        /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
.container {
    min-height: 100%;
    height: 100%;
    margin: 0 auto -155px;
}

.row.content {
    height: 1500px
}

/* Set gray background color and 100% height */
.sidenav {
    background-color: #f1f1f1;
    height: 100%;
}

/* Set black background color, white text and some padding */
footer {
    background-color: #555;
    color: white;
    padding: 15px;
}

/* On small screens, set height to 'auto' for sidenav and grid */
@media screen and (max-width: 767px) {
    .sidenav {
        height: auto;
        padding: 15px;
    }

    .row.content {
        height: auto;
    }
}
textarea {
    resize: none;
}
</style>
</head>

<body>
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header"><button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1" aria-expanded="false"><span class="sr-only">Toggle
                    navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a
                class="navbar-brand" href="/">BerrySoft TestCase</a></div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/">Главная страница</a></li>
                <li><a href="/new">Новая статья</a></li>
            </ul>
        </div>

        </nav>
            <!-- main content start -->
            <div class="col-sm-12">
                <form action="/articles">
                    <div>
                    </div>
                </form>
                <form method="POST" action="/articles">
                    <div class="form-group"><label for="author">Имя Автора</label><input required name="article[author]" type="text"
                            class="form-control" id="author" placeholder="Имя автора"></div>
                    <div class="form-group"><label for="description">Короткое описание</label><input required name="article[description]" autocomplete="off" type="text" class="form-control"
                            id="description" placeholder="Короткое описание"></div>
                    <div class="form-group"><label  for="body">Текст статьи</label>
                            <textarea wrap="hard"  required name="article[text]" class="form-control" rows="10" autocomplete="off"></textarea>
                        </div>

                    <input type="submit" class="btn btn-default" value="Отправить">
                </form>
                <!-- <footer class="">
                    <p>Footer Text</p>
                </footer> -->
            </div>
            <!-- container-fluid -->
</body>

</html>