<!DOCTYPE html>
<html lang="ru">

<head>
  <title>Добавить новость</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<link rel="stylesheet" href="assets/style.css">
</head>

<body>

  <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header"><button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1" aria-expanded="false"><span class="sr-only">Toggle
                    navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a
                class="navbar-brand" href="/">BerrySoft TestCase</a></div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/">Главная страница</a></li>
                <li><a href="/new">Новая статья</a></li>
            </ul>
        </div>

        </nav>
            <!-- main content start -->
            <div class="col-sm-12">
                <form action="/articles">
                    <div>
                    </div>
                </form>
                <form method="POST" action="/articles">
                    <div class="form-group"><label for="author">Имя Автора</label>


                    <input value="<?= $formData['author'] ?? ''; ?>" name="article[author]" type="text"
                            class="form-control has-feedback" id="author" placeholder="Имя Автора" ></div>
                    <div class="form-group"><label for="description">Короткое описание</label>

                    <input value="<?= $formData['description'] ?? ''; ?>" name="article[description]" autocomplete="off" type="text" class="form-control"
                            id="description" placeholder="Короткое описание"></div>
                    <div class="form-group"><label  for="body">Текст статьи</label>

                            <textarea wrap="hard" name="article[text]" class="form-control" rows="10" autocomplete="off"><?= $formData['text'] ?? ''; ?></textarea>
                        </div>

                    <input type="submit" class="btn btn-default" value="Отправить">
                </form>
            </div>

</body>

</html>