<?php 
use function App\Renderer\render;

?>
<?= render('common/head', ['title' => $title]); ?>

    <!-- Brand and toggle get grouped for better mobile display -->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/new">New</a></li>
        <li><a href="#">Link</a></li>
      </ul>
      <form action="/articles" class="navbar-form navbar-right" method="POST">
        <div class="form-group">
            <input type="hidden" name="_method" value="delete">
            <input type="hidden" name="truncate" value="true" id="truncate">
        </div>
        <button type="submit" class="btn btn-default">delete All Posts</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div><!-- /.navbar-collapse -->

    </nav>
    <div class="row content">
    <?= render('common/pager', ['pages' => $pages]); ?>
      <!-- SIDEBAR START -->

      <!-- END SIDEBAR -->
      <!-- main content start -->

      <div class="col-sm-12">
        <?php if (empty($articles)): ?>
        <h1>Не создано ни одной новости</h1>
        <?php endif; ?>
        <?php foreach ($articles as $article): ?>

        <article>
          <hr>
          <h2>
            <a href="/article/<?= $article['id']; ?>"><?= $article['description']; ?> </a>
          </h2>
          <h5><span class="glyphicon glyphicon-time"></span>
            Post by
            <?= $article['author_id']; ?>, at

            <?php echo (new \DateTime($article['created_at']))->format('Y-m-d H:i:s'); ?>
          </h5>
          <p>
            <?= $article['text']; ?>
            
          </p>
          <hr>
        </article>

        <?php endforeach; ?>

      </div>
    </div>
<?= render('common/pager', ['pages' => $pages]); ?>
<?= render('common/foot');
