</div>
</div>
</div>

<!-- Footer -->
<footer class="page-footer font-small cyan darken-3">
  <div class="text-center center-block">
    <br />
    <a href="https://github.com/fey/berrytest"><i id="social-github" class="fa fa-github fa-3x social"></i></a>
    <a href="mailto:feycot@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
  </div>
  </div>
  <!-- Footer Elements -->
</footer>
<!-- Footer -->
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<?php if (isset($comments)) : ?>
  <script src="/assets/comments.js"></script>
<?php endif; ?>

</html>