<!DOCTYPE html>
<html lang="en">

<head>
  <title><?= $title ?? 'Страница без заголовка'; ?></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="/assets/style.css">
  <link rel="shortcut icon" href="/assets/favicon.ico">
</head>

<body>
  <div class="container">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=""><a href="/">Главная страница</a></li>
        <li class=""><a href="/new">Добавить новость</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div>

    </nav>
    <div class="row content">
      <div class="col-sm-12">