<!DOCTYPE html>
<html lang="en">

<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;} 
    }
  </style>
</head>

<body>

  <div class="container">

    <!-- Brand and toggle get grouped for better mobile display -->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/new">New</a></li>
        <li><a href="#">Link</a></li>
      </ul>
      <form action="/articles" class="navbar-form navbar-right" method="POST">
        <div class="form-group">
            <input type="hidden" name="_method" value="delete">
            <input type="hidden" name="truncate" value="true" id="truncate">
        </div>
        <button type="submit" class="btn btn-default">delete All Posts</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div><!-- /.navbar-collapse -->

    </nav>
    <div class="row content">
      <nav aria-label="...">
        <ul class="pager">
          <li class="previous"><a href="#"><span aria-hidden="true">&larr;</span> Older</a></li>
          <li class="next"><a href="#">Newer <span aria-hidden="true">&rarr;</span></a></li>
        </ul>
      </nav>
      <!-- SIDEBAR START -->

      <!-- END SIDEBAR -->
      <!-- main content start -->

      <div class="col-sm-12">
        <?php if (empty($articles)): ?>
        <h1>Не создано ни одной новости</h1>
        <?php endif; ?>
        <?php foreach ($articles as $article): ?>

        <article>
          <hr>
          <h2>
            <a href="/article/<?= $article['id']; ?>"><?= $article['description']; ?> </a>
          </h2>
          <h5><span class="glyphicon glyphicon-time"></span>
            Post by
            <?= $article['author_id']; ?>, at

            <?php echo (new \DateTime($article['created_at']))->format('Y-m-d H:i:s'); ?>
          </h5>
          <p>
            <?= $article['text']; ?>
            
          </p>
          <hr>
        </article>

        <?php endforeach; ?>

      </div>
    </div>
    <nav aria-label="...">
      <ul class="pager">
        <li class="previous"><a href="#"><span aria-hidden="true">&larr;</span> Older</a></li>
        <li class="next"><a href="#">Newer <span aria-hidden="true">&rarr;</span></a></li>
      </ul>
    </nav>
    <footer class="">
      <p>Footer Text</p>
    </footer>
  </div>
  <!-- container-fluid -->



</body>

</html>