<article id="<?= $article->getId(); ?>">
<h2><?php if (isset($comments)): ?> <a href="/">&larr;</a> 
<?php endif; ?>
  <a href="/article/<?= $article->getId(); ?>"><?= $article->getTitle(); ?></a>
            
          </h2>
          <h5 "><span class="glyphicon glyphicon-time"></span>
            Автор
            <?= $article->getAuthor(); ?>,

            <?= $article->getCreatedAt(); ?>
          </h5>
          <?php if (isset($comments)): ?>
          <?= $article->getTextbody(); ?>
          <?php else: ?>
          <p>
              <h4>
              <?= $article->getDescription(); ?>
            </h4>
          </p>
          <?php endif; ?>
</article>

