<form class="answer-form" id="form-for-<?= isset($comment) ? $comment->getId() : '0'; ?>" role="form" method="POST" action="/comments">
    <div class="form-group"><label for="author">Имя Автора</label>
        <?php if (isset($errors['author'])) : ?>
            <p class="alert alert-danger"><?= $errors['author']; ?></p>
        <?php endif; ?>
        <input value="<?= $author; ?>" name="comment[author]" type="text" class="form-control has-feedback comment-author" id="author" placeholder="Имя Автора">
    </div>

    <div class="form-group">
        <?php if (isset($errors['author'])) : ?>
            <p class="alert alert-danger"><?= $errors['body']; ?></p>
        <?php endif; ?>
        <textarea wrap="hard" name="comment[body]" class="form-control comment-body" rows="5" cols="100" autocomplete="off"><?= $formData['body'] ?? ''; ?></textarea>
    </div>
    <input id="parentId" name="comment[parent_id]" type="hidden" value="<?= isset($comment) ? $comment->getId() : '0'; ?>">
    <input id="parentId" name="comment[article_id]" type="hidden" value="<?= $article->getId(); ?>">
    <button type="submit" class="btn btn-success">Submit</button>
</form>